### ISSUE TITLE
Start where you are — build crypto community, with crypto community — make an Oscar worthy movie that is governed by Ethereum smart contracts and an NFT game — imperfection is okay, iterative improvement is a must

### ISSUE THREAD

**Issue by sumeetpareek** [artsy-entrepreneurs/CryptoMentee#1]
## TASK

Start where you are — build crypto community, with crypto community — make an Oscar worthy movie that is governed by Ethereum smart contracts and an NFT game — imperfection is okay, iterative improvement is a must

## DONE WHEN 

- [ ] point all links on this project's [homepage](https://github.com/artsy-entrepreneurs/CryptoMentor-CryptoMentee) to clear relevant information .. currently they point back to this issue
- [ ] reachout to the first 21 potential CryptoMentors to help bootstrap this effort .. find them on twitter and/or discord
- [ ] create the first 3 CryptoMentor NFT's on OpenSea .. without gas fees or custom smart contract code .. goal is to learn those things to create the NFT game 

## CHECKLIST 

- [ ] item
- [ ] item
- [ ] item
- [ ] item
- [ ] item
- [ ] item
- [ ] item
- [ ] item
